### ISSUE TITLE
Version 1.3.0 is not compatible with NetBox 3.3.10

### ISSUE THREAD

**Issue by knobix** [DanSheps/netbox-secretstore#105]
### Plugin version

v1.3.0

### NetBox version

v3.3.10

### Python version

3.9

### Steps to Reproduce

- Have NetBox v3.3.10 and the `netbox-secretstore` plugin v1.3.0 installed
- Issue `python3.9 manage.py migrate`

### Expected Behavior

There should be no errors.

### Observed Behavior

```
Traceback (most recent call last):
  File "/usr/local/share/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 95, in wrapped
    saved_locale = translation.get_language()
  File "/usr/local/lib/python3.9/site-packages/django/utils/translation/__init__.py", line 210, in get_language
    return _trans.get_language()
  File "/usr/local/lib/python3.9/site-packages/django/utils/translation/__init__.py", line 65, in __getattr__
    if settings.USE_I18N:
  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 87, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 74, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 183, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/share/netbox/netbox/settings.py", line 684, in <module>
    plugin_config.validate(PLUGINS_CONFIG[plugin_name], VERSION)
  File "/usr/local/share/netbox/extras/plugins/__init__.py", line 101, in validate
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Plugin netbox_secretstore requires NetBox maximum version 3.3.9.
```

**Comment by knobix** [comment]
NB: There is a similar issue #101, but it was reported for NetBox 3.4-beta and presumably affects all releases of NetBox 3.4 as well.

**Comment by cjwagz** [comment]
Same issue in NetBox 3.4.1, installed this morning.
