### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by jboisdequin** [DanSheps/netbox-secretstore#112]
### Plugin version

1.4.1

### NetBox version

v3.3.8

### Python version

3.9

### Steps to Reproduce

Following the installation doc, after adding:
```
PLUGINS = [
    'netbox_secretstore',
]
```
in configuration.py
Running the migration fails with:
```
root@netbox-upgrade-001:/opt/netbox$ ./venv/bin/python -V
Python 3.9.16
root@netbox-upgrade-001:/opt/netbox$ ./venv/bin/python netbox/manage.py migrate
Traceback (most recent call last):
  File "/opt/netbox-3.3.8/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox-3.3.8/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/netbox-3.3.8/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/opt/netbox-3.3.8/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/netbox-3.3.8/venv/lib/python3.9/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/opt/netbox-3.3.8/venv/lib/python3.9/site-packages/django/contrib/admin/apps.py", line 27, in ready
    self.module.autodiscover()
  File "/opt/netbox-3.3.8/venv/lib/python3.9/site-packages/django/contrib/admin/__init__.py", line 50, in autodiscover
    autodiscover_modules("admin", register_to=site)
  File "/opt/netbox-3.3.8/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 58, in autodiscover_modules
    import_module("%s.%s" % (app_config.name, module_to_search))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/netbox-3.3.8/venv/lib/python3.9/site-packages/netbox_secretstore/admin.py", line 5, in <module>
    from .forms import ActivateUserKeyForm
  File "/opt/netbox-3.3.8/venv/lib/python3.9/site-packages/netbox_secretstore/forms/__init__.py", line 1, in <module>
    from .secrets import *
  File "/opt/netbox-3.3.8/venv/lib/python3.9/site-packages/netbox_secretstore/forms/secrets.py", line 8, in <module>
    from extras.forms import CustomFieldImportForm, CustomFieldFilterForm, CustomFieldBulkEditForm, CustomFieldForm, TagForm
ImportError: cannot import name 'CustomFieldImportForm' from 'extras.forms' (/opt/netbox-3.3.8/netbox/extras/forms/__init__.py)
```

### Expected Behavior

I'm expecting the migration script to be successful

### Observed Behavior

The error reports a python import error:
`ImportError: cannot import name 'CustomFieldImportForm' from 'extras.forms' (/opt/netbox-3.3.8/netbox/extras/forms/__init__.py)`

**Comment by kemeris2000** [comment]
I have the same problem.

**Comment by DeemGit** [comment]
... /opt/netbox-3.3.8/ ...
Plugin v1.4 supports only netbox 3.4+
If you are running netbox 3.3.8 try v1.3

**Comment by kemeris2000** [comment]
I missed that, thank you DeemGit.

**Comment by DanSheps** [comment]
As per @DeemGit, 1.4 only supports NetBox 3.4
