### ISSUE TITLE
TemplateSyntaxError at /plugins/netbox_secretstore/secret-roles/

### ISSUE THREAD

**Issue by abhi1693** [DanSheps/netbox-secretstore#55]
### Plugin version

master

### netbox-plugin-extensions version

1.0.9

### NetBox version

3.1.0

### Python version

3.8

### Steps to Reproduce

1. Add user key
2. Go to secret roles vi navigation menu

```
Internal Server Error: /plugins/netbox_secretstore/secret-roles/
Traceback (most recent call last):
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'plugin_add_button'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/asaharan/PycharmProjects/netbox/netbox/utilities/views.py", line 93, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/asaharan/PycharmProjects/netbox/netbox/netbox/views/generic.py", line 197, in get
    return render(request, self.template_name, context)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/template/defaulttags.py", line 965, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/template/base.py", line 522, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 16: 'plugin_add_button', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
[12/Dec/2021 02:54:37] "GET /plugins/netbox_secretstore/secret-roles/ HTTP/1.1" 500 239137

```

### Expected Behavior

The secret role page should be opened

### Observed Behavior

Secret role page crashes with template errors

**Comment by DanSheps** [comment]
You need to follow the instructions, specifically regarding the netbox_plugin_extensions plugin
