### ISSUE TITLE
Unable to unlock secrets

### ISSUE THREAD

**Issue by abhi1693** [DanSheps/netbox-secretstore#68]
### Plugin version

v1.0.16

### netbox-plugin-extensions version

None

### NetBox version

v3.2.1

### Python version

3.8

### Steps to Reproduce

1. Add a user key from the UI
2. Create a secret role named: `Administrators`
3. Create a new secret for a device/vm. It does not matter which, the issue occurs for both. Use the below values

```
Device: Your device
Role: Administrators
Name: admin
Plaintext: P@ssw0rd@123
Confirm: P@ssw0rd@123
```

4. Go to the device page and click on the `unlock` option for the secret. As soon as you provide the private key the error occurs.

### Expected Behavior

The secret should be unlocked without any issues

### Observed Behavior

```
Internal Server Error: /api/plugins/netbox_secretstore/secrets/1/
Traceback (most recent call last):
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/netbox_secretstore/api/views.py", line 100, in retrieve
    secret.decrypt(self.master_key)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/netbox_secretstore/models/secrets.py", line 405, in decrypt
    raise Exception("Must define ciphertext before unlocking.")
Exception: Must define ciphertext before unlocking.

```

The only way I have been able to recover from this error is to delete my secret and create again after which this never happens. It seems like unless the private key is not provided in the session this issue always occurs and the key is only requested by the UI upon unlocking.

**Comment by DanSheps** [comment]
I am not sure how you managed this, but you have somehow saved the secret without specifying your session key.  This shouldn't be possible.  

It is likely your password is stored in plaintext in the database and as the iv is consumed as the first 16 bytes it is possible that there is no password left to display.  For example, a 8 character ASCII text ('testtest') is only 16 bytes.

I don't think this is a bug in the current version, it is possible this was a bug in the past.
