### ISSUE TITLE
Unable to unlock secrets

### ISSUE THREAD

**Issue by abhi1693** [DanSheps/netbox-secretstore#77]
### Plugin version

v1.2.0

### netbox-plugin-extensions version

None

### NetBox version

v3.2.2-dev

### Python version

3.8

### Steps to Reproduce

The issue has already been explained in #68. Since it was closed without investigating, here is a video in a fresh project with just this plugin installed and still misbehaves as mentioned before.

https://user-images.githubusercontent.com/5083532/164059861-5f75c011-3cf7-426b-b3de-6046a5448a48.mp4

### Expected Behavior

Should be able to view the secret after unlocking

### Observed Behavior

The code crashes with `Must define ciphertext before unlocking.`

**Comment by DanSheps** [comment]
I am not sure how you got "It was not investigated" from my comment, but rest assured I attempted to reproduce it at the time, as well as just now again.

I am not able to reproduce following your steps.  Unfortunately, without being able to reproduce it I can't investigate it further.  You should be prompted for a dialog right before you save the secrets.  Are you getting any messages on your developer console?

**Comment by abhi1693** [comment]
Nothing shows up in the developer console. So far, I have only encountered this error when adding the very first secret and seems to be working fine after that. However, I'll keep an eye out and will share more if I encounter this issue again today.

**Comment by p4plus2** [comment]
I can confirm I have had the issue and not found a good fix yet.  Same steps to reproduce the issue.  It is not entirely consistent though.  Would anything else be helpful to track down the bug?

**Comment by DanSheps** [comment]
I want to confirm, can you both try "collectstatic" and dump your cached pages (or icognito mode works as well) and see if that improves the situation.

The problem right now is I need a reliable way to reproduce this

**Comment by abhi1693** [comment]
I have not reset my database since the day I posted this issue. So far, I have only had this issue 3-4 more times only. I have tried to capture the information from the developer console but the issue never happens when the window is open.

**Comment by DanSheps** [comment]
As mentioned, can you try the manage.py collectstatic and then dump your browser's cache

**Comment by abhi1693** [comment]
This happened again today. Here is what I found

![image](https://user-images.githubusercontent.com/5083532/169870153-82b83f2d-5d9e-4fe3-85ac-08c316db997b.png)

![image](https://user-images.githubusercontent.com/5083532/169870273-9b625dd9-2e35-4b03-ac89-17b8962a090e.png)

```
Internal Server Error: /api/plugins/netbox_secretstore/secrets/1/
Traceback (most recent call last):
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/netbox_secretstore/api/views.py", line 100, in retrieve
    secret.decrypt(self.master_key)
  File "/home/asaharan/PycharmProjects/netbox/venv/lib/python3.8/site-packages/netbox_secretstore/models/secrets.py", line 407, in decrypt
    raise Exception("Must define ciphertext before unlocking.")
Exception: Must define ciphertext before unlocking.
[23/May/2022 16:54:38] "GET /api/plugins/netbox_secretstore/secrets/1/ HTTP/1.1" 500 136227

```

**Comment by abhi1693** [comment]
While trying to figure out a way to programmatically add secrets for a virtual machine, I saw this in the logs and the end result was the error shared in the issue above

Even though I did not provide a session key, it still went ahead and created an instance of `Secret` with pk=72
```
Form validation was successful
Unable to proceed: No session key was provided with the request
Modified secret testuser (PK: 72)
```

cc @DanSheps

**Comment by DanSheps** [comment]
I will take a look when I have time.

**Comment by DanSheps** [comment]
Could you try the latest version?

**Comment by abhi1693** [comment]
I think you can recreate it this way. For the same user unlock a secret using the UI. Then without logging out, via API unlock the same secret. Finally, go to the UI and try unlocking anything and it will give errors. This much is reproducible for every time with/without the use of preserve key in the API

**Comment by DanSheps** [comment]
Did you try the latest version?
